name: remote ssh command
on: 
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
  
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }} 
          script: |
            cd prj/CleanArch
            git pull origin main
            docker stop cleanarch
            docker rm cleanarch
            docker rmi ca14
            docker build -t ca14 .
            docker run --name cleanarch -p 80:8000 -d -e DBUSER=root -e DBPASS="" -e DBHOST=mysqldb -e DBNAME=dockersql -e DBPORT=3306 -e JWT_KEY="tU645c134n4Rch1t3ctuR3" --link mysqldb ca14
            



